/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHENPrivacyAuctionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auctionBids"
      | "auctions"
      | "callbackDeclareWinner"
      | "createAuction"
      | "declareWinner"
      | "getAuctionStats"
      | "nextAuctionId"
      | "placeEncryptedBid"
      | "protocolId"
      | "terminateAuction"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuctionCreated"
      | "AuctionTerminated"
      | "DecryptionFulfilled"
      | "EncryptedBidPlaced"
      | "WinnerDeclared"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "auctionBids",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "auctions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackDeclareWinner",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuction",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "declareWinner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuctionStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextAuctionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "placeEncryptedBid",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "terminateAuction",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "auctionBids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "auctions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "callbackDeclareWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "declareWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuctionStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextAuctionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "placeEncryptedBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "terminateAuction",
    data: BytesLike
  ): Result;
}

export namespace AuctionCreatedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    creator: AddressLike,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    creator: string,
    deadline: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    creator: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionTerminatedEvent {
  export type InputTuple = [auctionId: BigNumberish, terminator: AddressLike];
  export type OutputTuple = [auctionId: bigint, terminator: string];
  export interface OutputObject {
    auctionId: bigint;
    terminator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionFulfilledEvent {
  export type InputTuple = [requestID: BigNumberish];
  export type OutputTuple = [requestID: bigint];
  export interface OutputObject {
    requestID: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EncryptedBidPlacedEvent {
  export type InputTuple = [auctionId: BigNumberish, bidder: AddressLike];
  export type OutputTuple = [auctionId: bigint, bidder: string];
  export interface OutputObject {
    auctionId: bigint;
    bidder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerDeclaredEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    winner: AddressLike,
    highestBid: BigNumberish,
    lowestBid: BigNumberish,
    averageBid: BigNumberish,
    bidCount: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    winner: string,
    highestBid: bigint,
    lowestBid: bigint,
    averageBid: bigint,
    bidCount: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    winner: string;
    highestBid: bigint;
    lowestBid: bigint;
    averageBid: bigint;
    bidCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHENPrivacyAuction extends BaseContract {
  connect(runner?: ContractRunner | null): FHENPrivacyAuction;
  waitForDeployment(): Promise<this>;

  interface: FHENPrivacyAuctionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auctionBids: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [[string, string] & { bidder: string; amount: string }],
    "view"
  >;

  auctions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        boolean,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        creator: string;
        item: string;
        description: string;
        deadline: bigint;
        terminated: boolean;
        decryptionPending: boolean;
        winnerDeclared: boolean;
        highestBidEncrypted: string;
        lowestBidEncrypted: string;
        sumBidsEncrypted: string;
        highestBidPlain: bigint;
        lowestBidPlain: bigint;
        averageBidPlain: bigint;
        bidCount: bigint;
        winner: string;
      }
    ],
    "view"
  >;

  callbackDeclareWinner: TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  createAuction: TypedContractMethod<
    [_item: string, _description: string, _deadline: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  declareWinner: TypedContractMethod<
    [auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAuctionStats: TypedContractMethod<
    [auctionId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string] & {
        bidCount: bigint;
        averageBid: bigint;
        highestBid: bigint;
        lowestBid: bigint;
        winner: string;
      }
    ],
    "view"
  >;

  nextAuctionId: TypedContractMethod<[], [bigint], "view">;

  placeEncryptedBid: TypedContractMethod<
    [auctionId: BigNumberish, encInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  terminateAuction: TypedContractMethod<
    [auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auctionBids"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [[string, string] & { bidder: string; amount: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "auctions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        boolean,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        creator: string;
        item: string;
        description: string;
        deadline: bigint;
        terminated: boolean;
        decryptionPending: boolean;
        winnerDeclared: boolean;
        highestBidEncrypted: string;
        lowestBidEncrypted: string;
        sumBidsEncrypted: string;
        highestBidPlain: bigint;
        lowestBidPlain: bigint;
        averageBidPlain: bigint;
        bidCount: bigint;
        winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "callbackDeclareWinner"
  ): TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createAuction"
  ): TypedContractMethod<
    [_item: string, _description: string, _deadline: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "declareWinner"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAuctionStats"
  ): TypedContractMethod<
    [auctionId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string] & {
        bidCount: bigint;
        averageBid: bigint;
        highestBid: bigint;
        lowestBid: bigint;
        winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextAuctionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "placeEncryptedBid"
  ): TypedContractMethod<
    [auctionId: BigNumberish, encInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "terminateAuction"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AuctionCreated"
  ): TypedContractEvent<
    AuctionCreatedEvent.InputTuple,
    AuctionCreatedEvent.OutputTuple,
    AuctionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionTerminated"
  ): TypedContractEvent<
    AuctionTerminatedEvent.InputTuple,
    AuctionTerminatedEvent.OutputTuple,
    AuctionTerminatedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionFulfilled"
  ): TypedContractEvent<
    DecryptionFulfilledEvent.InputTuple,
    DecryptionFulfilledEvent.OutputTuple,
    DecryptionFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "EncryptedBidPlaced"
  ): TypedContractEvent<
    EncryptedBidPlacedEvent.InputTuple,
    EncryptedBidPlacedEvent.OutputTuple,
    EncryptedBidPlacedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerDeclared"
  ): TypedContractEvent<
    WinnerDeclaredEvent.InputTuple,
    WinnerDeclaredEvent.OutputTuple,
    WinnerDeclaredEvent.OutputObject
  >;

  filters: {
    "AuctionCreated(uint256,address,uint256)": TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;
    AuctionCreated: TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;

    "AuctionTerminated(uint256,address)": TypedContractEvent<
      AuctionTerminatedEvent.InputTuple,
      AuctionTerminatedEvent.OutputTuple,
      AuctionTerminatedEvent.OutputObject
    >;
    AuctionTerminated: TypedContractEvent<
      AuctionTerminatedEvent.InputTuple,
      AuctionTerminatedEvent.OutputTuple,
      AuctionTerminatedEvent.OutputObject
    >;

    "DecryptionFulfilled(uint256)": TypedContractEvent<
      DecryptionFulfilledEvent.InputTuple,
      DecryptionFulfilledEvent.OutputTuple,
      DecryptionFulfilledEvent.OutputObject
    >;
    DecryptionFulfilled: TypedContractEvent<
      DecryptionFulfilledEvent.InputTuple,
      DecryptionFulfilledEvent.OutputTuple,
      DecryptionFulfilledEvent.OutputObject
    >;

    "EncryptedBidPlaced(uint256,address)": TypedContractEvent<
      EncryptedBidPlacedEvent.InputTuple,
      EncryptedBidPlacedEvent.OutputTuple,
      EncryptedBidPlacedEvent.OutputObject
    >;
    EncryptedBidPlaced: TypedContractEvent<
      EncryptedBidPlacedEvent.InputTuple,
      EncryptedBidPlacedEvent.OutputTuple,
      EncryptedBidPlacedEvent.OutputObject
    >;

    "WinnerDeclared(uint256,address,uint32,uint32,uint32,uint256)": TypedContractEvent<
      WinnerDeclaredEvent.InputTuple,
      WinnerDeclaredEvent.OutputTuple,
      WinnerDeclaredEvent.OutputObject
    >;
    WinnerDeclared: TypedContractEvent<
      WinnerDeclaredEvent.InputTuple,
      WinnerDeclaredEvent.OutputTuple,
      WinnerDeclaredEvent.OutputObject
    >;
  };
}
